### ISSUE TITLE
Check markdown formatting

### ISSUE THREAD

**Issue by tmorrell** [AuthorCarpentry/planning#9]
Check that the markdown formatting is consistent in https://github.com/AuthorCarpentry/orcid-profile and https://github.com/AuthorCarpentry/dois-citation-data.  In particular, reformat challenge questions using the formatting described in https://github.com/AuthorCarpentry/lesson-template/issues/2

**Comment by dtwrub** [comment]
orcid-profile markdown formatting checked and formatted challenge questions according to template

**Comment by dtwrub** [comment]
dois-citation-data markdown formatting checked and formatted challenge questions according to template
